wonderpasnavi/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts' 
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

wonderpasnavi/memo/urls.py
from django.urls import path
from . import views

app_name='memo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

wonderpasnavi/wonderpasnavi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('memo.urls', namespace='memo')),
]

wonderpasnavi/accounts/models.py
from django.db import models

# Create your models here.

wonderpasnavi/memo/models.py
from django.db import models

# Create your models here.

wonderpasnavi/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView): 
    form_class = UserCreationForm  
    success_url = reverse_lazy('login') 
    template_name = 'accounts/signup.html' 

wonderpasnavi/memo/views.py
from django.views import View
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required


# Create your views here.

class userlist(LoginRequiredMixin, TemplateView):
    template_name = "memo/index.html"

    def get(self, request, *args, **kwargs):
        context = super(userlist, self).get_context_data(**kwargs)
        context['text'] = 'Login OK!!'
        return render(self.request, self.template_name, context)
    
    @login_required
    def index(request):
        return HttpResponse('Login OK!!')
    
class IndexView(View):
    def get(self, request):
        return HttpResponse('Hello, this is the Index View')

wonderpasnavi/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% block title %}sign up{% endblock %}
{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

wonderpasnavi/memo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block content %}{% endblock %}
        {% include 'menu.html' %}
    </body>
    </html>

wonderpasnavi/memo/templates/memo/index.html
{% extends "base.html" %}
{% block title %}memo - index - {% endblock %}
{% block content %}
<div><h1>memo index </h1></div>
<div>{{ text }}</div>
{% endblock %}

wonderpasnavi/memo/templates/menu.html
{% load static %}
<ul>
    <li><a href="{% url 'accounts:signup' %}">signup</a></li>
    <li><a href="{% url 'login' %}">login</a></li>
    <li><a href="{% url 'logout' %}">logout</a></li>
    <li><a href="{% url 'memo:index' %}">top</a></li>
</ul>